language: android

jdk:
  - oraclejdk8

env:
    global:
        - GOROOT_BOOTSTRAP=$GOROOT

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - pushd $ANDROID_HOME
    - rm -rf tools
    - wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O tools.zip
    - unzip -q tools.zip
    - popd
    - touch $HOME/.android/repositories.cfg
    - yes | sdkmanager
        "build-tools;28.0.0"
        ndk-bundle
        "platforms;android-28"
      >/dev/null
      


before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "newcode1"
      - git config --local user.email "newcode1@email.com"
      - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
    provider: releases
    skip-cleanup: true
    api_key: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    file: app/build/outputs/apk/debug/app-debug.apk


script:
    - ./gradlew assembleDebug check
    - ls -la
    - ls -la app/build/outputs/apk/debug
